/* Generated by deploy/generate_sitemaps.py — do not edit by hand. */
export const factoryPublicImages = [
  "/images/factory/pinjin-concrete-pump-manufacturing.webp",
  "/images/factory/pinjin-construction-machinery-factory-loading.webp",
  "/images/factory/pinjin-diesel-machinery-factory-dispatch.webp",
  "/images/factory/pinjin-equipment-storage.webp",
  "/images/factory/pinjin-machinery-assembly-area.webp",
  "/images/factory/pinjin-machinery-workshop-overhead-crane.webp",
  "/images/factory/pinjin-production-workshop.webp",
  "/images/factory/pinjin-trailer-concrete-pump-assembly.webp",
  "/images/factory/pinjin-xingjiawan-concrete-machinery-factory.webp",
] as const;

export const applicationPublicImages = [
  "/images/applications/pinjin-concrete-equipment-highway-infrastructure.webp",
  "/images/applications/pinjin-concrete-pump-building-construction.webp",
  "/images/applications/pinjin-concrete-pump-construction-site.webp",
  "/images/applications/pinjin-hydraulic-mortar-spraying-machine-site.webp",
  "/images/applications/pinjin-mortar-spraying-machine-building-interior.webp",
] as const;

export const heroPublicImages = [
  "/images/hero/pinjin-machinery-factory-xingtai-china.webp",
] as const;

export const productPublicImagesBySlug: Record<string, readonly string[]> = {
  "diesel-120-concrete-pump": [
    "/images/products/diesel-120-concrete-pump/main.webp",
    "/images/products/diesel-120-concrete-pump/catalog.webp",
  ],
  "diesel-30-concrete-pump": [
    "/images/products/diesel-30-concrete-pump/main.webp",
    "/images/products/diesel-30-concrete-pump/catalog.webp",
  ],
  "diesel-40-concrete-pump": [
    "/images/products/diesel-40-concrete-pump/main.webp",
    "/images/products/diesel-40-concrete-pump/catalog.webp",
  ],
  "diesel-50-concrete-pump": [
    "/images/products/diesel-50-concrete-pump/main.webp",
    "/images/products/diesel-50-concrete-pump/catalog.webp",
  ],
  "diesel-60-concrete-pump": [
    "/images/products/diesel-60-concrete-pump/main.webp",
    "/images/products/diesel-60-concrete-pump/catalog.webp",
  ],
  "diesel-mixer-integrated-pump": [
    "/images/products/diesel-mixer-integrated-pump/main.webp",
    "/images/products/diesel-mixer-integrated-pump/catalog.webp",
  ],
  "electric-10-series-concrete-pump": [
    "/images/products/electric-10-series-concrete-pump/main.webp",
    "/images/products/electric-10-series-concrete-pump/catalog.webp",
  ],
  "electric-15-concrete-pump": [
    "/images/products/electric-15-concrete-pump/main.webp",
    "/images/products/electric-15-concrete-pump/catalog.webp",
  ],
  "electric-20-concrete-pump": [
    "/images/products/electric-20-concrete-pump/main.webp",
    "/images/products/electric-20-concrete-pump/catalog.webp",
  ],
  "electric-30-concrete-pump": [
    "/images/products/electric-30-concrete-pump/main.webp",
    "/images/products/electric-30-concrete-pump/catalog.webp",
  ],
  "electric-40-concrete-pump": [
    "/images/products/electric-40-concrete-pump/main.webp",
    "/images/products/electric-40-concrete-pump/catalog.webp",
  ],
  "electric-50-concrete-pump": [
    "/images/products/electric-50-concrete-pump/main.webp",
    "/images/products/electric-50-concrete-pump/catalog.webp",
  ],
  "electric-60-concrete-pump": [
    "/images/products/electric-60-concrete-pump/main.webp",
    "/images/products/electric-60-concrete-pump/catalog.webp",
  ],
  "electric-80-concrete-pump": [
    "/images/products/electric-80-concrete-pump/main.webp",
    "/images/products/electric-80-concrete-pump/catalog.webp",
  ],
  "electric-low-pressure-40-concrete-pump": [
    "/images/products/electric-low-pressure-40-concrete-pump/main.webp",
    "/images/products/electric-low-pressure-40-concrete-pump/catalog.webp",
  ],
  "electric-low-pressure-60-concrete-pump": [
    "/images/products/electric-low-pressure-60-concrete-pump/main.webp",
    "/images/products/electric-low-pressure-60-concrete-pump/catalog.webp",
  ],
  "hbt80-16-concrete-pump": [
    "/images/products/hbt80-16-concrete-pump/main.webp",
    "/images/products/hbt80-16-concrete-pump/catalog.webp",
  ],
  "hbt8018-concrete-pump": [
    "/images/products/hbt8018-concrete-pump/main.webp",
    "/images/products/hbt8018-concrete-pump/catalog.webp",
  ],
  "integrated-mixer-pump": [
    "/images/products/integrated-mixer-pump/main.webp",
    "/images/products/integrated-mixer-pump/catalog.webp",
  ],
  "lz-60-diesel-concrete-pump": [
    "/images/products/lz-60-diesel-concrete-pump/main.webp",
    "/images/products/lz-60-diesel-concrete-pump/catalog.webp",
  ],
  "lz-80-diesel-concrete-pump": [
    "/images/products/lz-80-diesel-concrete-pump/main.webp",
    "/images/products/lz-80-diesel-concrete-pump/catalog.webp",
  ],
  "rural-diesel-concrete-pump": [
    "/images/products/rural-diesel-concrete-pump/main.webp",
    "/images/products/rural-diesel-concrete-pump/catalog.webp",
  ],
  "tractor-4100-concrete-pump": [
    "/images/products/tractor-4100-concrete-pump/main.webp",
    "/images/products/tractor-4100-concrete-pump/catalog.webp",
  ],
};
